# Generated by Django 5.2.17 on 2026-09-12 07:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('year_started', models.DateTimeField(auto_now_add=True)),
                ('year_graduated', models.DateTimeField(blank=True, null=True)),
                ('activities', models.TextField()),
                ('achievements', models.TextField()),
            ],
        ),
    ]
