# Generated by Django 5.2.17 on 2026-09-13 04:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='achievements',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='education',
            name='activities',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='education',
            name='year_started',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
