# Generated by Django 5.2.17 on 2026-09-19 10:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent', models.DateTimeField(auto_now_add=True)),
                ('related_experience', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sender', models.CharField(default='Anonymous', max_length=30)),
                ('image_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
