# Generated by Django 5.2.17 on 2026-09-26 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_project_starred_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='hearted_by',
            field=models.ManyToManyField(blank=True, related_name='hearted_testimonials', to=settings.AUTH_USER_MODEL),
        ),
    ]
